version: '3.9'
services:  

  app:
    build: .
    image: contas:1.0
    container_name: contas_app
    restart: unless-stopped
    tty: true
    volumes:
       - ./:/var/www
    networks:
      - default
  
  nginx:
    image: nginx:alpine
    container_name: contas_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "222:80"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - default
    depends_on:
      - app

networks:
  default:
    driver: bridge