version: '3.9'
services:  

  #PHP Service
  app:
    build: .
    image: contas:1.0
    container_name: contas_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - default
  
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: contas_webserver
    restart: unless-stopped
    tty: true
    ports:
      # - "80:80"
      # - "443:443"
      - "5000:80"
      - "6000:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default
    depends_on:
      - app

  # mysql:
  #   image: mysql:8.0.29
  #   container_name: p-mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   # networks:
  #   #   - p-rede
  #   environment:
  #     MYSQL_ROOT_PASSWORD: braip

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   container_name: p-phpmyadmin
  #   restart: always
  #   # networks:
  #   #   - p-rede
  #   ports:
  #     - 4000:80
  #   environment:
  #     - PMA_ARBITRARY=1

networks:
  default:
    driver: bridge