name: Deploy Hostgator

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: update packages
      run: sudo apt-get update
      
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup PHP without composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
      
    - name: Create folder build
      run: mkdir build
    
    - name: Instalando as dependencias
      run: composer install --optimize-autoloader --no-dev
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
        
    - name: copy project to folder
      run: |
        echo "release ${{ steps.date.outputs.date }}"
        zip -vr build/${{ steps.date.outputs.date }}.zip ./ -x '*.DS_Store' '*.git*' '*.github*'

    - name: copy file deploy.php
      run: |
        cp ./versions/deploy.php build/
      
    - name: List files in the repository
      run: |
        ls build
        
    - name: FTP upload
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: ./
        local-dir: ${{ github.workspace }}/build/
        
#     - name: Copy script
#       run: cp ./scripts/zip-code.php ../
    
#     - name: Execute script
#       run: |
#         cd ../
#         pwd
#         ls
#         php zip-code.php ${{ secrets.FTP_SERVER }} ${{ secrets.FTP_USER }} ${{ secrets.FTP_PASS }}

#     - name: Setup PHP without composer
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.1'
#         tools: composer:v2
        
#     - name: Install dependencies
#       run: |
#         php -v &&
#         composer install
  
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#     - name: Update code server
#       run: echo "🎉 updateing code..."
