name: Deploy Hostgator

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: update packages
      run: sudo apt-get update
      
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: Create folder build
      run: mkdir build
        
#     - name: copy project to folder
#       run: zip -vr build/josimar.zip ./ -x '*.DS_Store' '*.git*' '*.github*'
      
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
        
    - name: Copy script
      run: cp ./scripts/zip-code.php ../
    
    - name: Execute script
      run: \
        cd ../ ls && php zip-code.php ${{ secrets.FTP_SERVER }} ${{ secrets.FTP_USER }} ${{ secrets.FTP_PASS }}

#     - name: Setup PHP without composer
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.1'
#         tools: composer:v2
        
#     - name: Install dependencies
#       run: |
#         php -v &&
#         composer install
  
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#     - name: Update code server
#       run: echo "🎉 updateing code..."
