name: Deploy Hostgator

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: update packages
      run: sudo apt-get update
      
    - name: Check out repository code
      uses: actions/checkout@v3
        
    - name: copy project to folder
      run: zip -vr josimar.zip ${{ github.workspace }}/ -x '*.DS_Store' '*.git*' '*.github*'
      
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
        
#     - name: Setup PHP without composer
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.1'
#         tools: composer:v2
        
#     - name: Install dependencies
#       run: |
#         php -v &&
#         composer install
  
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#     - name: Update code server
#       run: echo "🎉 updateing code..."
